# Site
name: Marcel Schutte
description: Pragmatic Architecture Website
meta_description: Pragmatic Architecture Website
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
paginate: 6
baseurl:
email: 'marceljschutte+pragarch@gmail.com'
google_analytics: UA-103662447-9
disqus:
sharethis:

# Authors
authors:
  john:
    name: Marcel
    display_name: Marcel Schutte
    image: /assets/images/john.jpg
    email: marceljschutte+pragarch@gmail.com
    web: http://pragarchitect.github.io
    twitter:
    description: Hi, I am Marcel Schutte

# Plugins
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag

permalinks: pretty

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: 'category/:name/'

# Other
markdown: kramdown
highlighter: rouge

# SEO
twitter:
  username: pragarchitect
  card: summary

facebook:
  app_id:
  publisher: john.com
  admins:

social:
name: John Doe
links:
    - https://x.com/pragarchitect
    - https://www.linkedin.com/marceljschutte
    - https://github.com/pragarchitect
